name: "First-action"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev","main"]

jobs:
  1st-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Printing Something
        run: echo "Hello developer"
        shell: bash
  
  2nd-runner:
      - uses: actions/checkout@v2
      - name: installing Nodejs
        run: sudo apt install node
        shell: bash