name: "First-action"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev","main"]

jobs:
  First-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Printing Something
        run: echo "Hello developer"
        shell: bash
  
  Second-runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Apt Update
        run: apt update
        shell: bash

      - name: Installing Sudo
        run: apt install sudo
        
      - name: installing Nodejs
        run: sudo apt install node
        shell: bash